error_codes = {
        # "0":"*Succsess*",
        "0 7":"Power off - waiting for power request TRUE",
        "0 20":"Power on - ready to have GPL attach robot",
        "0 21":"21 GPL project attached to robot",
        "-1012":"*Joint out-of-range* Set robot joints within their range",
        "-1040":"*Position too far* Robot 1",
        "-1042":"*Can't change robot config* Robot 1",
        "-1600":"*Power off requested*",
        "-1009":"*No robot attached*",
        "-2800":"*Warning Parameter Mismatch*",
        "-2801":"*Warning No Parameters",
        "-2802":"*Warning Illegal move command*",
        "-2803":"*Warning Invalid joint angles*",
        "-2804":"*Warning: Invalid Cartesian coordinate values*",
        "-2805":"*Unknown command*  ",
        "-2806":"*Command Exception*",
        "-2807":"*Warning cannot set Input states*",
        "-2808":"*Not allowed by this thread*",
        "-2809":"*Invalid robot type*",
        "-2810":"*Invalid serial command*",
        "-2811":"*Invalid robot number*",
        "-2812":"*Robot already selected*",
        "-2813":"*Module not initialized*",
        "-2814":"*Invalid location index*",
        "-2816":"*Undefined location*",
        "-2817":"*Undefined profile*",
        "-2818":"*Undefined pallet*",
        "-2819":"*Pallet not supported*",
        "-2820":"*Invalid station index*",
        "-2821":"*Undefined station*",
        "-2822":"*Not a pallet*",
        "-2823":"*Not at pallet origin*"        
        }